import type { Metadata } from "next";

import "./globals.css";
import { Inter } from "next/font/google"; // ✅ Inter import kiya

// Inter font initialize
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"], // ✅ aap aur bhi weight add kar sakte ho
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        {/* ✅ Inter apply */}
        {children}
      </body>
    </html>
  );
}
